"""Add EmployeeSalary and extend Payroll

Revision ID: 77a94cc1d2a7
Revises: 904375d40c28
Create Date: 2026-08-22 10:39:21.827728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77a94cc1d2a7'
down_revision: Union[str, Sequence[str], None] = '904375d40c28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_salaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('basic_salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('allowances', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('deductions', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee_salaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_salaries_employee_id'), ['employee_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_employee_salaries_id'), ['id'], unique=False)

    with op.batch_alter_table('payrolls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('month', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('period_start', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('period_end', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('gross_salary', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('status', sa.Enum('DRAFT', 'PROCESSED', 'PAID', 'CANCELLED', name='payrollstatusenum'), nullable=True))
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('generated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('processed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('paid_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('allowances',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('deductions',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_payrolls_status'), ['status'], unique=False)
        batch_op.drop_column('effective_from')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payrolls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('effective_from', sa.DATE(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_payrolls_status'))
        batch_op.alter_column('deductions',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('allowances',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.drop_column('paid_at')
        batch_op.drop_column('processed_at')
        batch_op.drop_column('generated_at')
        batch_op.drop_column('comment')
        batch_op.drop_column('status')
        batch_op.drop_column('gross_salary')
        batch_op.drop_column('period_end')
        batch_op.drop_column('period_start')
        batch_op.drop_column('year')
        batch_op.drop_column('month')

    with op.batch_alter_table('employee_salaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_salaries_id'))
        batch_op.drop_index(batch_op.f('ix_employee_salaries_employee_id'))

    op.drop_table('employee_salaries')
    # ### end Alembic commands ###
