"""Add profile fields to Employee

Revision ID: 8ea1e21e9e7b
Revises: e98db58458f5
Create Date: 2026-08-22 10:11:41.221537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ea1e21e9e7b'
down_revision: Union[str, Sequence[str], None] = 'e98db58458f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('company_name', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('location', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('about', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('skills', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('certifications', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'certifications')
    op.drop_column('employees', 'skills')
    op.drop_column('employees', 'about')
    op.drop_column('employees', 'avatar_url')
    op.drop_column('employees', 'location')
    op.drop_column('employees', 'company_name')
    # ### end Alembic commands ###
