"""Add max_days to LeaveType

Revision ID: 904375d40c28
Revises: dfc0fad69e2b
Create Date: 2026-08-22 10:31:53.279123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '904375d40c28'
down_revision: Union[str, Sequence[str], None] = 'dfc0fad69e2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.alter_column('check_in',
               existing_type=sa.TIME(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('check_out',
               existing_type=sa.TIME(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('PENDING', 'APPROVED', 'REFUSED', 'CANCELLED', name='leavestatusenum'),
               existing_nullable=True)

    with op.batch_alter_table('leave_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_days', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_types', schema=None) as batch_op:
        batch_op.drop_column('max_days')

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'APPROVED', 'REFUSED', 'CANCELLED', name='leavestatusenum'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)

    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.alter_column('check_out',
               existing_type=sa.DateTime(),
               type_=sa.TIME(),
               existing_nullable=True)
        batch_op.alter_column('check_in',
               existing_type=sa.DateTime(),
               type_=sa.TIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
