"""Add missing employee fields

Revision ID: c7114865c9a6
Revises: 85cc18592e9b
Create Date: 2026-08-22 13:29:35.871770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7114865c9a6'
down_revision: Union[str, Sequence[str], None] = '85cc18592e9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('marital_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('nationality', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('nationality')
        batch_op.drop_column('marital_status')
        batch_op.drop_column('gender')
        batch_op.drop_column('date_of_birth')

    # ### end Alembic commands ###
