"""Add worked_hours and extra_hours to Attendance

Revision ID: dfc0fad69e2b
Revises: 8ea1e21e9e7b
Create Date: 2026-08-22 10:22:28.236568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfc0fad69e2b'
down_revision: Union[str, Sequence[str], None] = '8ea1e21e9e7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('worked_hours', sa.Float(), nullable=True))
    op.add_column('attendances', sa.Column('extra_hours', sa.Float(), nullable=True))
    op.alter_column('attendances', 'check_in',
               existing_type=sa.TIME(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('attendances', 'check_out',
               existing_type=sa.TIME(),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendances', 'check_out',
               existing_type=sa.DateTime(),
               type_=sa.TIME(),
               existing_nullable=True)
    op.alter_column('attendances', 'check_in',
               existing_type=sa.DateTime(),
               type_=sa.TIME(),
               existing_nullable=True)
    op.drop_column('attendances', 'extra_hours')
    op.drop_column('attendances', 'worked_hours')
    # ### end Alembic commands ###
